- .gitignore
- mkdocs.yml
- poetry.lock
- pyproject.toml
This adds a few minor, nice-to-have github integrations for our docs. These are:
1. Visual component that links back and displays github repo information in top bar
2. Edit docs link for submitting quick edits.
3. Display of docs git history details, including authors, created date, and last edit date.
Screenshots below:
.
.
.
> Add GitHub integrations to docs

- docs/tutorials/02_alias_sampling_basic.ipynb
- src/bartiq/compilation/_evaluate.py
- src/bartiq/compilation/_symbolic_function.py
- tests/compilation/data/evaluate_test_data.json
This PR fixes two problems:
- Issue with evaluating expressions such as `log(120)` (#32)
- Correctly pruning linked_params during evaluation.
When we perform evaluation, `input_params` that got evaluated get removed, and so should `linked_params`. However, previous `linked_params` were only removed from the top-level routine, not from all their children. 
Closes: #32
> fix: assigning value to evaluated expressions and pruning linked_params

- docs/limitations.md
- src/bartiq/integrations/latex.py
- tests/compilation/test_compile.py
- tests/compilation/test_symbolic_function.py
- tests/integrations/test_latex.py
I noticed we use stale terminology in a couple of places, this PR just updates that.
> chore: remove "estimator" naming

- src/bartiq/compilation/_compile.py
- tests/compilation/data/compile_test_data.yaml
> feat: don't add children costs during compilation

- .gitignore
- src/bartiq/_routine.py
- src/bartiq/compilation/_compile.py
- src/bartiq/compilation/_evaluate.py
- src/bartiq/compilation/_symbolic_function.py
- tests/compilation/data/compile_test_data.yaml
- tests/compilation/data/evaluate_test_data.yaml
- tests/routine/test_routine.py
- tests/test_routing.py
WiP version of the compilation handling proper non-empty root name.
I didn't have time to clean it up, I want to get rid of `absolute_path_without_root` and just deal with this behavior using `exclude_root_name` flag in `absolute_path`.
Closes #53
> 53 fix handling root name

- docs/data/alias_sampling_basic.json
- docs/reference.md
- docs/tutorials/01_basic_example.ipynb
- docs/tutorials/02_alias_sampling_basic.ipynb
- poetry.lock
- pyproject.toml
- src/bartiq/_routine.py
- src/bartiq/compilation/_compile.py
- src/bartiq/verification.py
- tests/compilation/test_compile.py
- tests/compilation/test_evaluate.py
- tests/integrations/test_latex.py
- tests/precompilation/test_precompile.py
- tests/routine/test_routine.py
- tests/test_routing.py
- tests/test_verification.py
- tests/utilities.py
Closes #18 
- It required update to QREF 0.5.0.
- Haven't checked if API docs render properly, still need to do that. Probably also might add some info about it to the tutorial.
> feat: routine verification

- src/bartiq/integrations/qref.py
- tests/integrations/test_qref_integration.py
- Context: This pull request resolves issue #81 to ensure that local variables are correctly passed when converting qref to the bartiq routines.
- Concise description of the implemented solution: This PR modifies the _routine_v1_to_bartiq_routine function to ensure that local variables are correctly passed and included in the resulting routine. 
- Dependencies: No new dependencies are added.
> Fixed the bug not passing local_variables from qref to bartiq.

- docs/tutorials/01_basic_example.ipynb
- docs/tutorials/02_alias_sampling_basic.ipynb
- poetry.lock
- pyproject.toml
- src/bartiq/_routine.py
- src/bartiq/compilation/_compile.py
- src/bartiq/compilation/_symbolic_function.py
- src/bartiq/integrations/latex.py
- src/bartiq/integrations/qref.py
- src/bartiq/symbolics/utilities.py
- src/bartiq/verification.py
- tests/compilation/data/compile_test_data.yaml
- tests/compilation/data/evaluate_test_data.yaml
- tests/compilation/test_compile.py
- tests/compilation/test_core.py
- tests/compilation/test_symbolic_function.py
- tests/integrations/test_latex.py
- tests/integrations/test_qref_integration.py
- tests/test_verification.py
Currently, we store local variables as a list of strings, each of them of the form "symbol = expression", e.g.:
```python
local_variables = ["a = x + y", "b = 42"]
```
However, each time such variables are processed, this lists of strings gets converted to a dictionary. Therefore, it is only natural to make `local_variables` a dictionary in the first place, so that the example above looks like:
```python
local_variables = {"a": "x+y", "b": "42"}
```
which is what this PR does.
While refactoring this, some functions became obsolete and were thus removed from the codebase entirely as a part of this PR.
> refactor!: Make local_variables a dictionary instead of a list of strings

- src/bartiq/integrations/qref.py
- tests/integrations/test_qref_integration.py
Consider the following two routines, which might seem identical at first glance:
```python
routine1 = Routine(name="root", ports={"in": {"name": "in", "direction": "input", "size": 1}})
routine2 = Routine(name="root", ports={"in": Port.model_validate({"name": "in", "direction": "input", "size": 1})})
```
The reason why those two should be identical is that the dictionary for the input port in `routine1` has to be converted to `Port` anyway. In both cases `routine.ports["in"].direction` should be the same, and equal to string "input", because we have our models configured with [`use_enum_values`](https://docs.pydantic.dev/2.0/api/config/#pydantic.config.ConfigDict). However, for whatever reason, in the second case the actual direction is a member of `PortDirection` enum. This is not a …
> fix: Fix port direction handling in Qref export

- src/bartiq/symbolics/sympy_backends.py
- src/bartiq/symbolics/sympy_interpreter.py
- tests/symbolics/test_sympy_interpreter.py
Currently, we use very peculiar logic for handling multiplicity. If `multiplicity` is given symbolic parameters, it is not possible to substitute them with numbers and obtain a concrete value (instead of `multiplicity(p, n)` symbol). This is because if initial evaluation of multiplicity fails, a dummy `Function("multiplicity")` is placed in the expression, and obviously there is no way for Sympy to know any rules about evaluating substitution into this object.
This PR implements multiplicity as a proper custom Sympy function. This has two main benefits:
- Simplified logic in `create_function`.
- Roundtrip through `serialize` is no longer needed to trigger multiplicity evaluation, which has obvious performance benefits.
I think this closes https://github.com/PsiQ/bartiq/issues/25
> feat: Properly implement multiplicity as Sympy custom function

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .dockerignore
- .gitignore
Fixes https://github.com/PsiQ/bartiq/issues/47
Aligns the development container with the documentation with regards to tools and dependencies.
- Uses non-root user
- Uses poetry
- Uses all extra developer dependencies
Works as expected in my tests, both on local VSCode and Codespaces environments.
> 47 update devcontainer to include developer dependencies

- docs/data/basic_example.json
Fixes #104 
This PR adds input_params to basic_example.json since it fails with the routine verification.
bartiq.errors.BartiqCompilationError: Found the following issues with the provided routine before the compilation started: ['N is present in linked_params, but not in input_params.\n']
> Added input params to basic_example.json

- poetry.lock
- pyproject.toml
Bumped QREF dependency to `0.7.0`, to enable usage of some QoL features.
> chore: bump qref version to 0.7.0

- src/bartiq/transform.py
- tests/test_transform.py
This PR solves issue #106 by adding the `remove_decomposed` parameter to the `add_aggregated_resources` function.
In certain use cases, it is necessary to preserve the original resources after they have been aggregated. Previously, the `add_aggregated_resources` function automatically removed the original resources after aggregation.
- A boolean parameter `remove_decomposed` has been added to the `add_aggregated_resources` function.
- **If `remove_original=True`** (default): The original resource is removed after aggregation.
- **If `remove_original=False`**: The original resource is retained, and its type is marked as "other" to distinguish it from other resources (a straightforward approach; however, there may be more optimized solutions.)
- Test cases have been added to validate the …
> fix: Add parameter to decide wheter remove resource in aggregation function 

- src/bartiq/compilation/__init__.py
- src/bartiq/compilation/_common.py
- src/bartiq/compilation/_compile.py
- src/bartiq/compilation/_evaluate.py
- tests/compilation/test_evaluate.py
Currently, the constraints are taken into account only when compiling routine. However, constraint validation can also occur during an evaluation (if constraint turned to be ambiguous during the compilation). This PR implements handling of constraints during evaluation. Similarly to the compilation phase, while evaluating, the trivial constraints are dropped, vilated constraints raise an error, and ambiguous constraints are preserved.
- N/A I have updated documentation.
> Fix constraint evaluation

- docs/javascript/config.js
- mkdocs.yml
Rendering LaTeX formulas in docs didn't work properly (as notice by @mstechly ). This PR fixes it.
- N/A I have included test cases validating introduced feature/fix.
- N/A I have updated documentation.
> fix: Fix LaTeX rendering in docs

- poetry.lock
- pyproject.toml
- src/bartiq/_routine.py
- src/bartiq/compilation/_compile.py
This uses the recently introduced `ensure_routine` from `qref.functools` to streamline conversions between Qref objects and Bartiq native dataclasses. Relies on psiq/qref#122 to be merged first (and then Qref to be released).
> feat: Use ensure_routine to streamline conversion from Qref to Bartiq

- src/bartiq/symbolics/ast_parser.py
- tests/symbolics/test_sympy_interpreter.py
Currently Bartiq messes up parsing functions and variables that contain word "lambda" (e.g. `calc_lambda`). This fixes it.
> Fix handling of function names with "lambda" in them

- docs/tutorials/03_advanced_examples.ipynb
- mkdocs.yml
Adds a link to the newest tutorial and removes broken link in the `concepts` section.
> docs: add advanced tutorial to docs

- src/bartiq/_routine.py
- src/bartiq/symbolics/backend.py
- src/bartiq/symbolics/sympy_backends.py
- tests/compilation/data/compile/general.yaml
- tests/compilation/data/compile/passthroughs.yaml
- tests/compilation/data/compile/ports_and_topology.yaml
- tests/compilation/data/evaluate/constants.yaml
- tests/compilation/data/evaluate/general.yaml
- tests/compilation/test_evaluate.py
- tests/compilation/test_preprocessing.py
- tests/symbolics/test_sympy_backend.py
While working on several features, we noticed that there are some limitations to the backend interface, namely:
1. It is not possible to obtain native Python objects from expressions. There is a `serialize` method that always returns string, and there is `value_of` method that either returns a number OR `None` if it is not possible to convert an expression to number. There is no single function that would convert expressions representing numbers to numbers, and other expressions to strings.
2. While manipulating symbolic expressions is easy through arithmetic operators, there's not really a way for applying function to symbolic expressions. The current solution involves going through `backend.as_expression`, e.g.: `backend.as_expression(f"sin({backend.serialize(some_expr)})")` which a) is …
> feat: Enable casting to native types and obtaining backend-native functions

- src/bartiq/symbolics/sympy_backends.py
- tests/symbolics/test_sympy_backend.py
Fixes bug described in #143. The fix is achieved by correcting the usage of `identity_for_numbers`.
> fix: Fix defining function in case some of them evaluate to constant

- src/bartiq/integrations/latex.py
- src/bartiq/symbolics/sympy_backends.py
- tests/symbolics/test_sympy_backend.py
- tests/symbolics/test_sympy_interpreter.py
- tests/test_analysis.py
Closes #146 
The problem was solved by dynamically defining proper sympy functions that can be evaluated when needed instead of relying on a success of a single call to the user defined function.
Additionally, this PR contains a boy-scout cleanup of the warnings raised in all our tests. At least when tested locally, the tests don't emit any warnings. Most warnings were just filtered out (as they are known and expected warnings), two of them were fixed because they resulted from typo.
> fix: Substitution of functions is no longer sensitive to order of functions dictionary

- src/bartiq/errors.py
- src/bartiq/repetitions.py
- src/bartiq/symbolics/backend.py
- src/bartiq/symbolics/sympy_backends.py
- src/bartiq/transform.py
- tests/symbolics/test_sympy_backend.py
Adds min and max functions to symbolic backend and refactors `sum` to `sequence_sum` (and same for `prod`).
> feat: add min and max to backend

- src/bartiq/integrations/latex.py
- tests/integrations/test_latex.py
Fixes issue when we try to render in latex routine where one of the local variables has multiple underscores.
> fix: add escape for _ in local_variables in latex

- src/bartiq/integrations/jupyter/routine_explorer.py
- src/bartiq/integrations/latex.py
- tests/integrations/test_latex.py
I was finding an error when trying to explore uncompiled routines with port sizes set to `None`. The previous implementation was passing these into sympy as strings, which was causing an error during sympy's evaluation.
This simply handles those cases by bypassing the sympy-expression-to-latex pass.
In addition, the following boyscout changes were made:
1. Removing the unused constant `MAX_RESOURCE_SECTIONS`, which I introduced accidentally in a previous PR.
2. Decorates `explore_routine` with `accepts_all_qref_types`.
> Support port sizes when rendering with latex

- src/bartiq/compilation/postprocessing.py
- tests/compilation/test_postprocessing.py
In the current implementation, he highwater for an empty routine is -infinity. That's because for such a routine the list of nonzero watermarks is empty, and in sympy maximum of an empty list is is -infinity. This is not a big problem, but it may make highwater look strange for some virtual routines, so this PR introduces a safeguard against that.
> fix: Ensure highwater is 0 for empty routines

- docs/concepts/compilation.md
- docs/reference.md
- docs/tutorials/01_basic_example.ipynb
- docs/tutorials/02_alias_sampling_basic.ipynb
- docs/tutorials/03_advanced_examples.ipynb
- src/bartiq/compilation/__init__.py
- src/bartiq/compilation/_compile.py
- tests/compilation/test_compile.py
- tests/compilation/test_derived_resources.py
- tests/compilation/test_postprocessing.py
- tests/compilation/test_repetitions.py
This PR adds `CompilationFlags`, a `enum.Flag` class that are used to modify the compilation process. 
This replaces the use of the keywords `skip_verification` and `allow_transitive_resources` in `bartiq.compilation._compile.compile`. 
- Instead of `skip_verification=True`, use `compilation_flags = CompilationFlags.SKIP_VERIFICATION`
- Instead of `allow_transitive_resources=False`, use `compilation_flags = CompilationFlags.EXPAND_RESOURCES`.
Flags can be combined bitwise, i.e. `compilation_flags = FLAG1 | FLAG2`.
Other minor updates:
- Fixed a bug where transitive resources were not being evaluated correctly in repetitions. 
- Added `bartiq.compilation` to the docs API reference.
> feat: created `CompilationFlags` enum

- src/bartiq/compilation/_common.py
- src/bartiq/compilation/_compile.py
- src/bartiq/symbolics/sympy_backend.py
- src/bartiq/symbolics/sympy_interpreter.py
- tests/compilation/data/highwater.yaml
- tests/compilation/test_derived_resources.py
- tests/symbolics/test_sympy_backend.py
- tests/symbolics/test_sympy_interpreter.py
This PR introduced performance improvements for calculating derived resources, as well as specific improvements to the qubit highwater calculation.
So far, the process of calculating derived resources wasn't respecting the compilation flags. Therefore, even if other resources weren't being expanded for usual resources, they were being expanded for the purpose of computing the derived ones. This was undermining our previous optimization efforts, as the highwater (which is a derived resource) calculation is currently the biggest bottleneck. This PR solves this problem by temporarily replacing child resources with dummy variables, unless EXPAND_RESOURCES flag is passed. Such "dummified" routine is passed to the resource-computing functions, which can access resource values per usual - which …
> feat: more performant calculation of derived resources

- src/bartiq/integrations/latex.py
- tests/integrations/test_latex.py
This PR is meant to close https://github.com/PsiQ/bartiq/issues/163.
**Context**
The rendering issue arises when calling the ``symbols`` SymPy function, which under the hood attempts to create SymPy ``Symbol`` objects and then, once done, prints them.
A ``Symbol`` object in SymPy is also a ``Printable`` object, whose [``_repr_latex_`` method](https://github.com/sympy/sympy/blob/da6d1f3cb324ad0bf74d123d85c390029be997ce/sympy/core/_print_helpers.py#L54) is being called in a Jupyter environment. However, this method defaults to a behaviour that interprets certain input suffixes as default modifiers. The example string from #163 had the specific `cal` suffix, which happens to be one of the modifiers ([see here](https://github.com/sympy/sympy/blob/da6d1f3cb324ad0bf74d123d85c390029be997ce/sympy/ …
> fix: avoid SymPy ``LatexPrinter`` modifiers to change subscripted parameter symbols

- src/bartiq/symbolics/sympy_interpreter.py
- tests/symbolics/test_sympy_interpreter.py
As reported by @seangreenaway , our custom `Max` function fails to evaluate for numerical arguments if at least one of them is of rational type. This PR fixes it adds relevant tests.
> fix: make custom max correctly evaluate when numeric arguments are rationals

- src/bartiq/symbolics/sympy_interpreter.py
- tests/symbolics/test_sympy_interpreter.py
This PR makes `ntz(0)` equal to -1, as discussed via other communication channels.
Also cleans up relevant test cases.
> fix: make ntz(0) = -1
